/**
 * Regenerates the machine-readable discovery documents that must stay in sync
 * with the files they point at:
 *
 *   - .well-known/agent-skills/index.json  (sha256 digest per SKILL.md)
 *   - sitemap.xml                          (<lastmod> per page)
 *
 * Run standalone (`node scripts/build-seo.js`) or via `npm run build`, which
 * calls it before copying files into dist/.
 */
var fs = require('fs');
var path = require('path');
var crypto = require('crypto');

var ROOT = path.join(__dirname, '..');
var ORIGIN = 'https://einkchess.fun';

function sha256(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

// --- Agent Skills discovery index (RFC v0.2.0) ---------------------------
var skillsDir = path.join(ROOT, '.well-known/agent-skills');
var skills = fs.readdirSync(skillsDir)
  .filter(function (entry) {
    return fs.statSync(path.join(skillsDir, entry)).isDirectory();
  })
  .sort()
  .map(function (name) {
    var skillPath = path.join(skillsDir, name, 'SKILL.md');
    var source = fs.readFileSync(skillPath, 'utf8');

    // Pull `description:` out of the YAML frontmatter so the index can never
    // disagree with the skill itself.
    var match = source.match(/^description:\s*(.+)$/m);
    if (!match) {
      throw new Error('Missing `description:` in frontmatter of ' + skillPath);
    }

    return {
      name: name,
      type: 'skill-md',
      description: match[1].trim(),
      url: '/.well-known/agent-skills/' + name + '/SKILL.md',
      digest: 'sha256:' + sha256(skillPath)
    };
  });

var index = {
  $schema: 'https://schemas.agentskills.io/discovery/0.2.0/schema.json',
  skills: skills
};

fs.writeFileSync(
  path.join(skillsDir, 'index.json'),
  JSON.stringify(index, null, 2) + '\n',
  'utf8'
);
console.log('Wrote .well-known/agent-skills/index.json (' + skills.length + ' skills)');

// --- Sitemap -------------------------------------------------------------
// Canonical pages only. Legacy monoliths (chess-old.html, puzzles-old.html) and
// the superseded play-bot.html are excluded and disallowed in robots.txt.
var PAGES = [
  { loc: '/', file: 'index.html', changefreq: 'weekly', priority: '1.0' },
  { loc: '/play-bot-v2.html', file: 'play-bot-v2.html', changefreq: 'weekly', priority: '0.9' },
  { loc: '/puzzles.html', file: 'puzzles.html', changefreq: 'weekly', priority: '0.9' },
  { loc: '/analysis.html', file: 'analysis.html', changefreq: 'monthly', priority: '0.7' },
  { loc: '/settings.html', file: 'settings.html', changefreq: 'monthly', priority: '0.5' }
];

var entries = PAGES.filter(function (page) {
  return fs.existsSync(path.join(ROOT, page.file));
}).map(function (page) {
  var lastmod = fs.statSync(path.join(ROOT, page.file)).mtime.toISOString().slice(0, 10);
  return [
    '  <url>',
    '    <loc>' + ORIGIN + page.loc + '</loc>',
    '    <lastmod>' + lastmod + '</lastmod>',
    '    <changefreq>' + page.changefreq + '</changefreq>',
    '    <priority>' + page.priority + '</priority>',
    '  </url>'
  ].join('\n');
});

var sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/build-seo.js — do not edit by hand.',
  '     https://www.sitemaps.org/protocol.html -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  entries.join('\n'),
  '</urlset>',
  ''
].join('\n');

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap, 'utf8');
console.log('Wrote sitemap.xml (' + entries.length + ' URLs)');
